# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 20:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0005_auto_20170217_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='mining_level',
            field=models.PositiveIntegerField(default=0, help_text='A numeric indication of the highest depth and breadth of package data collected through previous visits. Higher means more and deeper collection.'),
        ),
    ]
