# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 18:20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0011_auto_20180921_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='origin_date',
        ),
        migrations.AddField(
            model_name='package',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, help_text='The date that the package file was created, or when it was posted to its original download source.', null=True),
        ),
    ]
