# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 19:34
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0021_package_download_sha512'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='manifest_path',
            field=models.CharField(blank=True, help_text='A relative path to the manifest file if any, such as a Maven .pom or a npm package.json.', max_length=1024, null=True),
        ),
    ]
