# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 01:24
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0025_auto_20181030_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='license_expression',
            new_name='normalized_license',
        ),
    ]
