# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 02:24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0027_auto_20181030_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='code_type',
        ),
        migrations.AddField(
            model_name='package',
            name='contains_source_code',
            field=models.NullBooleanField(),
        ),
    ]
