# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 00:19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0031_auto_20190110_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['download_url']},
        ),
        migrations.RemoveField(
            model_name='package',
            name='uri',
        ),
        migrations.AlterField(
            model_name='package',
            name='download_url',
            field=models.CharField(db_index=True, help_text='A direct download URL.', max_length=2048, unique=True),
        ),
    ]
