# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-05 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0040_add_root_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['id']},
        ),
    ]
