# Generated by Django 4.0.4 on 2022-04-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0049_alter_resource_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='An optional JSON-formatted field to identify additional resource attributes.'),
        ),
    ]
