version: "3"

services:
  db:
    image: postgres:13
    env_file:
      - docker_purldb.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  web:
    build: .
    command: sh -c "
        python manage_purldb.py migrate &&
        python manage_purldb.py collectstatic --no-input --verbosity 0 --clear &&
        gunicorn purldb_project.wsgi:application --bind :8000 --timeout 600 --workers 8"
    env_file:
      - docker_purldb.env
    expose:
      - 8000
    volumes:
      - /etc/purldb/:/etc/purldb/
      - static:/var/purldb/static/
      - temp_data:/tmp/minecode/
    depends_on:
      - db

  visitor:
    build: .
    command: sh -c "
        wait-for-it web:8000 -- python manage_purldb.py seed &&
        python manage_purldb.py run_visit --ignore-robots --ignore-throttle"
    env_file:
      - docker_purldb.env
    volumes:
      - /etc/purldb/:/etc/purldb/
    profiles:
      - visit_and_map
    depends_on:
      - db
      - web # Ensure that potential db migrations run first

  mapper:
    build: .
    command: wait-for-it web:8000 -- python manage_purldb.py run_map
    env_file:
      - docker_purldb.env
    volumes:
      - /etc/purldb/:/etc/purldb/
    profiles:
      - visit_and_map
    depends_on:
      - db
      - web # Ensure that potential db migrations run first

  clearsync:
    build: .
    command: wait-for-it web:8000 -- clearsync --save-to-db  --verbose -n 3
    env_file:
      - docker_purldb.env
    volumes:
      - /etc/purldb/:/etc/purldb/
    profiles:
      - clearsync
    depends_on:
      - db
      - web # Ensure that potential db migrations run first

  clearindex:
    build: .
    command: wait-for-it web:8000 -- python manage_purldb.py run_clearindex
    env_file:
      - docker_purldb.env
    profiles:
      - clearsync
    depends_on:
      - db
      - web # Ensure that potential db migrations run first

  priority_queue:
    build: .
    command: wait-for-it web:8000 -- python manage_purldb.py priority_queue
    env_file:
      - docker_purldb.env
    volumes:
      - /etc/purldb/:/etc/purldb/
    profiles:
      - priority_queue
    depends_on:
      - db
      - web

  scheduler:
    build: .
    command: wait-for-it web:8000 -- python manage_purldb.py run_scheduler
    env_file:
      - docker_purldb.env
    volumes:
      - /etc/purldb/:/etc/purldb/
    depends_on:
      - redis
      - db
      - web

  rq_worker:
    build: .
    command: wait-for-it web:8000 -- python manage_purldb.py rqworker default
    env_file:
      - docker_purldb.env
    volumes:
      - /etc/purldb/:/etc/purldb/
      - temp_data:/tmp/minecode/
    depends_on:
      - redis
      - db
      - web

volumes:
  db_data:
  static:
  redis_data:
  temp_data:
