services:
  db:
    image: docker.io/library/postgres:17.10
    env_file:
      - docker.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    shm_size: "1gb"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/library/redis:8.8.0-alpine
    # Enable redis data persistence using the "Append Only File" with the
    # default policy of fsync every second. See https://redis.io/topics/persistence
    command: redis-server --appendonly yes --loglevel warning
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: wait-for-it --strict --timeout=60 db:5432 -- sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --no-input --verbosity 0 --clear &&
        gunicorn purldb.wsgi:application --bind :8000 --timeout 600 --workers 8"
    env_file:
      - docker.env
    expose:
      - 8000
    volumes:
      - .env:/opt/purldb/.env
      - /etc/purldb/:/etc/purldb/
      - temp_data:/tmp/minecode/
      - static:/var/purldb/static/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  priority_queue:
    build: .
    command: wait-for-it web:8000 -- python manage.py priority_queue
    env_file:
      - docker.env
    volumes:
      - .env:/opt/purldb/.env
      - /etc/purldb/:/etc/purldb/
    profiles:
      - priority_queue
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started

  scheduler:
    build: .
    command: wait-for-it web:8000 -- python manage.py run_scheduler
    env_file:
      - docker.env
    volumes:
      - .env:/opt/purldb/.env
      - /etc/purldb/:/etc/purldb/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started

  rq_worker:
    build: .
    command: wait-for-it web:8000 -- python manage.py rqworker default
    env_file:
      - docker.env
    volumes:
      - .env:/opt/purldb/.env
      - /etc/purldb/:/etc/purldb/
      - temp_data:/tmp/minecode/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started

volumes:
  db_data:
  static:
  redis_data:
  temp_data:
