include:
  - docker-compose.yml

services:
  visitor:
    build: .
    command: sh -c "
        python manage.py seed &&
        python manage.py run_visit --ignore-robots --ignore-throttle"
    env_file:
      - docker.env
    volumes:
      - /etc/purldb/:/etc/purldb/
    profiles:
      - visit_and_map
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started

  mapper:
    build: .
    command: python manage.py run_map
    env_file:
      - docker.env
    volumes:
      - /etc/purldb/:/etc/purldb/
    profiles:
      - visit_and_map
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started

  clearsync:
    build: .
    command: python manage.py clearsync --save-to-db  --verbose -n 3
    env_file:
      - docker.env
    volumes:
      - /etc/purldb/:/etc/purldb/
    profiles:
      - clearsync
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started

  clearindex:
    build: .
    command: python manage.py run_clearindex
    env_file:
      - docker.env
    profiles:
      - clearsync
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
