# Generated by Django 3.0.4 on 2020-03-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDitem',
            fields=[
                ('path', models.CharField(help_text='Path to the original file in the ClearlyDefined file storage.', max_length=2048, primary_key=True, serialize=False)),
                ('content', models.BinaryField(help_text='Actual gzipped JSON content.')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Date and time that this record was last modified.')),
            ],
        ),
    ]
