# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_auto_20160707_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceuri',
            name='data',
            field=models.TextField(blank=True, help_text='Text content of the file represented by this ResourceURI. This contains the data that was fetched or extracted from a remote ResourceURI such as HTML or JSON.', null=True),
        ),
        migrations.AlterField(
            model_name='resourceuri',
            name='map_error',
            field=models.TextField(blank=True, help_text='Mapping errors messages. . When present this means the mapping failed.', null=True),
        ),
        migrations.AlterField(
            model_name='resourceuri',
            name='visit_error',
            field=models.TextField(blank=True, help_text='Visit errors messages. When present this means the visit failed.', null=True),
        ),
    ]
