# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0009_resourceuri_source_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceuri',
            name='mining_level',
            field=models.PositiveIntegerField(default=0, help_text='A numeric indication of the depth and breadth of data collected through this ResourceURI visit. Higher means more and deeper data.'),
        ),
    ]
