# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0012_auto_20170807_0444'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resourceuri',
            index=models.Index(fields=['is_visitable', 'last_visit_date', 'wip_date'], name='discovery_r_is_visi_29fde2_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceuri',
            index=models.Index(fields=['is_mappable', 'last_visit_date', 'wip_date', 'last_map_date', 'visit_error'], name='discovery_r_is_mapp_e362dc_idx'),
        ),
    ]
