# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0017_auto_20180619_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannableuri',
            name='package_id',
            field=models.PositiveIntegerField(help_text='The primary key of the Package that this ScannableURI is for', null=True),
        ),
    ]
