# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0018_scannableuri_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannableuri',
            name='scan_status',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'submitted'), (2, 'in progress'), (3, 'scanned'), (4, 'indexed'), (5, 'failed'), (6, 'timeout'), (7, 'scan index failed')], db_index=True, default=0, help_text='Status of the scan for this URI.'),
        ),
    ]
