# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0019_auto_20180716_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceuri',
            name='package_url',
            field=models.CharField(blank=True, db_index=True, help_text='Package URL for this resource. It stands for a package "mostly universal" URL.', max_length=2048, null=True),
        ),
    ]
