# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0021_auto_20181026_1635'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scannableuri',
            name='discovery_s_priorit_5b5e01_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourceuri',
            name='discovery_r_priorit_daf7b6_idx',
        ),
        migrations.RemoveField(
            model_name='resourceuri',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='scannableuri',
            name='rank',
        ),
        migrations.AddIndex(
            model_name='scannableuri',
            index=models.Index(fields=['-priority'], name='discovery_s_priorit_2f397f_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceuri',
            index=models.Index(fields=['-priority'], name='discovery_r_priorit_b8bce2_idx'),
        ),
    ]
