# Generated by Django 5.1.2 on 2024-10-30 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchcode", "0002_alter_approximatedirectorycontentindex_package_and_more"),
        ("packagedb", "0086_alter_party_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnippetIndex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.BinaryField(
                        db_index=True,
                        help_text="Binary form of a snippet fingerprint",
                        max_length=16,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        help_text="The Package that this snippet fingerprint is from",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packagedb.package",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        help_text="The Package that this snippet fingerprint is from",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packagedb.resource",
                    ),
                ),
            ],
        ),
    ]
