# Generated by Django 5.1.5 on 2025-02-21 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchcode", "0004_snippetindex_position_and_more"),
        ("packagedb", "0090_alter_packageactivity_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="StemmedSnippetIndex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.BinaryField(
                        db_index=True,
                        help_text="Binary form of a snippet fingerprint",
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "package",
                    models.ForeignKey(
                        help_text="The Package that this file is from",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packagedb.package",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        help_text="The Package that this snippet fingerprint is from",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packagedb.resource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
