# Generated by Django 4.1.2 on 2023-02-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minecode", "0022_auto_20190307_2332"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="resourceuri",
            new_name="minecode_re_is_visi_51562c_idx",
            old_name="minecode_r_is_visi_29fde2_idx",
        ),
        migrations.RenameIndex(
            model_name="resourceuri",
            new_name="minecode_re_is_mapp_78700f_idx",
            old_name="minecode_r_is_mapp_e362dc_idx",
        ),
        migrations.RenameIndex(
            model_name="resourceuri",
            new_name="minecode_re_priorit_a38996_idx",
            old_name="minecode_r_priorit_b8bce2_idx",
        ),
        migrations.RenameIndex(
            model_name="scannableuri",
            new_name="minecode_sc_scan_st_d6a459_idx",
            old_name="minecode_s_scan_st_21b64d_idx",
        ),
        migrations.RenameIndex(
            model_name="scannableuri",
            new_name="minecode_sc_priorit_bd9674_idx",
            old_name="minecode_s_priorit_2f397f_idx",
        ),
    ]
