# Generated by Django 4.1.2 on 2023-04-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minecode", "0028_priorityresourceuri"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorityresourceuri",
            name="has_processing_error",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When set to True (Yes), this field indicates that an error has occured when processing this URI.",
            ),
        ),
        migrations.AddField(
            model_name="priorityresourceuri",
            name="processing_error",
            field=models.TextField(
                blank=True,
                help_text="Processing errors messages. When present this means the processing failed.",
                null=True,
            ),
        ),
    ]
