# Generated by Django 4.1.2 on 2023-07-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minecode", "0029_priorityresourceuri_has_processing_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scannableuri",
            name="rescan_uri",
            field=models.BooleanField(
                default=False,
                null=True,
                blank=True,
                help_text="Flag indicating whether or not this URI should be rescanned and reindexed.",
            ),
        ),
    ]
