# Generated by Django 5.0.1 on 2024-02-16 00:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("minecode", "0033_scannableuri_populate_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scannableuri",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
