# Generated by Django 5.0.1 on 2024-02-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minecode", "0034_scannableuri_alter_uuid_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scannableuri",
            old_name="rescan_uri",
            new_name="reindex_uri",
        ),
    ]
