# Generated by Django 5.0.6 on 2024-06-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecode", "0035_create_scan_queue_workers_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorityresourceuri",
            name="addon_pipelines",
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text="A list of addon ScanCode.io pipeline to run.",
            ),
        ),
    ]
