# Generated by Django 5.0.1 on 2024-03-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecode", "0035_rename_rescan_uri_scannableuri_reindex_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="scannableuri",
            name="pipelines",
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text="A list of ScanCode.io pipeline names to be run for this scan",
            ),
        ),
    ]
