# Generated by Django 5.1.13 on 2026-03-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minecode", "0037_processingerror"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importableuri",
            name="has_processing_error",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When set to True (Yes), this field indicates that an error has occurred when processing this URI.",
            ),
        ),
        migrations.AlterField(
            model_name="priorityresourceuri",
            name="has_processing_error",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When set to True (Yes), this field indicates that an error has occurred when processing this URI.",
            ),
        ),
        migrations.AlterField(
            model_name="processingerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp set to the date of when this error occurred.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processingerror",
            name="service",
            field=models.CharField(
                blank=True,
                help_text="The name of the service running where the error occurred.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourceuri",
            name="has_map_error",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When set to True (Yes), this field indicates that an error has occurred when mapping this URI.",
            ),
        ),
        migrations.AlterField(
            model_name="resourceuri",
            name="has_visit_error",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When set to True (Yes), this field indicates that an error has occurred when visiting this URI.",
            ),
        ),
    ]
