# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 17:18
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Metadata collected for this package: this is a JSON-serialized ScannedPackage.'),
        ),
    ]
