# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 07:22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0003_auto_20160708_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='md5',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 checksum hex-encoded, as in md5sum.', max_length=32, null=True, verbose_name='MD5'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sha1',
            field=models.CharField(blank=True, db_index=True, help_text='SHA1 checksum hex-encoded, as in sha1sum.', max_length=40, null=True, verbose_name='SHA1'),
        ),
    ]
