# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 08:44
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0006_package_mining_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='file_name',
            new_name='filename',
        ),
    ]
