# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 00:40
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0009_auto_20180918_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='vcs_tool',
            field=models.CharField(blank=True, choices=[('git', 'git'), ('svn', 'subversion'), ('hg', 'mercurial'), ('bzr', 'bazaar'), ('cvs', 'cvs')], help_text='The type of VCS tool for this package.', max_length=16, null=True),
        ),
    ]
