# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 19:09
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0012_auto_20181001_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='download_checksums',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, help_text='A list of checksums for this download in hexadecimal and prefixed by the lowercased checksum algorithm and a colon e.g. sha1:c5095691347bd5ad3b5e180238c3914d16f05812', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, help_text='A list of keywords.', null=True, size=None),
        ),
    ]
