# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 19:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0014_remove_package_package_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='download_checksums',
        ),
    ]
