# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 19:11
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0016_auto_20181023_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='download_sha1',
            field=models.CharField(blank=True, db_index=True, help_text='SHA1 checksum hex-encoded, as in sha1sum.', max_length=40, null=True, verbose_name='download SHA1'),
        ),
    ]
