# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 19:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0017_auto_20181023_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='md5',
            new_name='download_md5',
        ),
    ]
