# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 19:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0018_auto_20181023_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='download_md5',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 checksum hex-encoded, as in md5sum.', max_length=32, null=True, verbose_name='download MD5'),
        ),
    ]
