# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 19:15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0020_package_download_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='download_sha512',
            field=models.CharField(blank=True, db_index=True, help_text='SHA512 checksum hex-encoded, as in sha512sum.', max_length=128, null=True, verbose_name='download SHA512'),
        ),
    ]
