# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 01:17
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0023_package_source_packages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='declared_licensing',
            new_name='declared_license',
        ),
    ]
