# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 01:17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0024_auto_20181030_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='declared_license',
            field=models.CharField(blank=True, help_text='The declared license mention or tag or text as found in a package manifest.', max_length=1024, null=True),
        ),
    ]
