# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 01:25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0026_auto_20181030_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='normalized_license',
            field=models.CharField(blank=True, help_text='The normalized license expression for this package as derived from its declared license.', max_length=1024, null=True),
        ),
    ]
