# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 16:16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0029_auto_20181127_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='download_md5',
            new_name='md5',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='download_sha1',
            new_name='sha1',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='download_sha256',
            new_name='sha256',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='download_sha512',
            new_name='sha512',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='vcs_repository',
            new_name='vcs_url'
        ),
        migrations.RemoveField(
            model_name='package',
            name='vcs_revision',
        ),
        migrations.RemoveField(
            model_name='package',
            name='vcs_tool',
        ),
    ]
