# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-08 21:26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0034_auto_20200407_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='git_sha1',
            field=models.CharField(blank=True, help_text='git SHA1 checksum hex-encoded', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_file',
            field=models.BooleanField(default=False, help_text='True if this Resource is a file, False if it is a Directory'),
        ),
        migrations.AddField(
            model_name='resource',
            name='sha256',
            field=models.CharField(blank=True, help_text='SHA256 checksum hex-encoded, as in sha256sum.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='sha512',
            field=models.CharField(blank=True, help_text='SHA512 checksum hex-encoded, as in sha512sum.', max_length=128, null=True),
        ),
    ]
