# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-23 19:42
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0036_auto_20200416_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(blank=True, help_text='Version of the package.', max_length=100, null=True),
        ),
    ]
