# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-29 20:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0037_auto_20200423_1242'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['type', 'namespace', 'name', 'version', 'qualifiers', 'subpath'], name='packagedb_p_type_e16a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['type'], name='packagedb_p_type_897e74_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['namespace'], name='packagedb_p_namespa_496980_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['name'], name='packagedb_p_name_c57c81_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['version'], name='packagedb_p_version_698cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['qualifiers'], name='packagedb_p_qualifi_2cabb2_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['subpath'], name='packagedb_p_subpath_cea832_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['download_url'], name='packagedb_p_downloa_da61f7_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['filename'], name='packagedb_p_filenam_789999_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['size'], name='packagedb_p_size_23b568_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['release_date'], name='packagedb_p_release_83260c_idx'),
        ),
    ]
