# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-09 19:10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0038_add_index_for_filter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Name of the package.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='namespace',
            field=models.CharField(blank=True, default='', help_text='Package name prefix, such as Maven groupid, Docker image owner, GitHub user or organization, etc.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='qualifiers',
            field=models.CharField(blank=True, default='', help_text='Extra qualifying data for a package such as the name of an OS, architecture, distro, etc.', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='subpath',
            field=models.CharField(blank=True, default='', help_text='Extra subpath within a package, relative to the package root.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(blank=True, default='', help_text='A short code to identify the type of this package. For example: gem for a Rubygem, docker for a container, pypi for a Python Wheel or Egg, maven for a Maven Jar, deb for a Debian package, etc.', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(blank=True, default='', help_text='Version of the package.', max_length=100),
            preserve_default=False,
        ),
    ]
