# Generated by Django 3.1.5 on 2021-02-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0044_add_history_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='license_expression',
            field=models.CharField(blank=True, help_text='The combined and normalized license expression for this Resource as derived from its detected license expressions', max_length=8192, null=True),
        ),
    ]
