# Generated by Django 3.1.5 on 2021-03-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0045_relax_license_expression_max_length_for_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='An optional JSON-formatted field to identify additional package attributes.'),
        ),
    ]
