# Generated by Django 4.1.2 on 2022-12-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0051_package_api_data_url_package_datasource_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="index_error",
            field=models.TextField(
                blank=True,
                help_text="Indexing errors messages. When present this means the indexing has failed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="last_indexed_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp set to the date of the last indexing. Used to track indexing status.",
                null=True,
            ),
        ),
    ]
