# Generated by Django 4.1.2 on 2023-04-25 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0053_packagerelation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={
                (
                    "download_url",
                    "type",
                    "namespace",
                    "name",
                    "version",
                    "qualifiers",
                    "subpath",
                )
            },
        ),
    ]
