# Generated by Django 4.1.2 on 2023-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0054_alter_package_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="copyright",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="license_expression",
        ),
        migrations.AddField(
            model_name="resource",
            name="authors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detected authors (and related detection details).",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="copyrights",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detected copyright statements (and related detection details).",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="emails",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detected emails (and related detection details).",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="extension",
            field=models.CharField(
                blank=True,
                help_text="File extension for this resource (directories do not have an extension).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="Descriptive file type for this resource.",
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="holders",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detected copyright holders (and related detection details).",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_binary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_key_file",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_media",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_text",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="license_expressions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detected license expressions.",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="licenses",
            field=models.JSONField(
                blank=True, default=list, help_text="List of license detection details."
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="mime_type",
            field=models.CharField(
                blank=True,
                help_text="MIME type (aka. media type) for this resource. See https://en.wikipedia.org/wiki/Media_type",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="File or directory name of this resource with its extension.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="package_data",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Package data detected from this CodebaseResource",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="programming_language",
            field=models.CharField(
                blank=True,
                help_text="Programming language of this resource if this is a code file.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detected URLs (and related detection details).",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional mapping of extra data key/values.",
            ),
        ),
    ]
