# Generated by Django 4.1.2 on 2023-05-04 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0055_remove_resource_copyright_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dependentpackage",
            old_name="requirement",
            new_name="extracted_requirement",
        ),
    ]
