# Generated by Django 4.1.2 on 2023-05-10 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0059_compute_package_license_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="contains_source_code",
        ),
        migrations.RemoveField(
            model_name="package",
            name="manifest_path",
        ),
    ]
