# Generated by Django 4.1.2 on 2023-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0060_remove_package_contains_source_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="detected_license_expression",
            field=models.TextField(blank=True, help_text="TODO"),
        ),
        migrations.AddField(
            model_name="resource",
            name="detected_license_expression_spdx",
            field=models.TextField(blank=True, help_text="TODO"),
        ),
        migrations.AddField(
            model_name="resource",
            name="license_clues",
            field=models.JSONField(
                blank=True, default=list, help_text="List of license clues."
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="license_detections",
            field=models.JSONField(
                blank=True, default=list, help_text="List of license detection details."
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="percentage_of_license_text",
            field=models.FloatField(blank=True, help_text="TODO", null=True),
        ),
    ]
