# Generated by Django 4.1.2 on 2023-05-12 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0062_compute_resource_license_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="license_expressions",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="licenses",
        ),
    ]
