# Generated by Django 4.1.2 on 2023-05-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0063_remove_resource_license_expressions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="package_content",
            field=models.CharField(
                choices=[
                    ("source", "Source"),
                    ("binary", "Binary"),
                    ("doc", "Doc"),
                    ("test", "Test"),
                ],
                help_text="Content of this Package as one of: source, binary, doc, test",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="package_set",
            field=models.TextField(
                blank=True,
                help_text="A UUID used to identify a group of related Packages",
                null=True,
            ),
        ),
    ]
