# Generated by Django 4.1.2 on 2023-05-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0063_remove_resource_license_expressions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="package_content",
            field=models.IntegerField(
                choices=[
                    (1, "Curation"),
                    (2, "Patch"),
                    (3, "Source Repo"),
                    (4, "Source Archive"),
                    (5, "Binary"),
                    (6, "Test"),
                    (7, "Doc"),
                ],
                help_text="Content of this Package as one of: Curation, Patch, Source Repo, Source Archive, Binary, Test, Doc",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="package_set",
            field=models.UUIDField(
                blank=True,
                help_text="A UUID used to identify a group of related Packages",
                null=True,
            ),
        ),
    ]
