# Generated by Django 4.1.2 on 2023-05-16 01:27

from django.db import migrations


def set_package_content_field(apps, schema_editor):
    Package = apps.get_model("packagedb", "Package")
    packages = Package.objects.filter(package_content__isnull=True)
    for package in packages:
        if 'source' in package.qualifiers:
            package.package_content = Package.PackageContentType.SOURCE
            package.save()


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0064_package_package_content_package_package_set"),
    ]

    operations = [
        migrations.RunPython(
            set_package_content_field,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
