# Generated by Django 4.1.2 on 2023-05-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0066_package_summary_alter_package_package_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="md5",
            field=models.CharField(
                blank=True,
                help_text="MD5 checksum hex-encoded, as in md5sum.",
                max_length=32,
                null=True,
                verbose_name="MD5",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="sha1",
            field=models.CharField(
                blank=True,
                help_text="SHA1 checksum hex-encoded, as in sha1sum.",
                max_length=40,
                null=True,
                verbose_name="SHA1",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA256 checksum hex-encoded, as in sha256sum.",
                max_length=64,
                null=True,
                verbose_name="SHA256",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="sha512",
            field=models.CharField(
                blank=True,
                help_text="SHA512 checksum hex-encoded, as in sha512sum.",
                max_length=128,
                null=True,
                verbose_name="SHA512",
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["md5"], name="packagedb_p_md5_db481b_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["sha1"], name="packagedb_p_sha1_2db469_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["sha256"], name="packagedb_p_sha256_1ead0b_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["sha512"], name="packagedb_p_sha512_2282a2_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["md5"], name="packagedb_r_md5_38fb8e_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["sha1"], name="packagedb_r_sha1_833621_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["sha256"], name="packagedb_r_sha256_02e049_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["sha512"], name="packagedb_r_sha512_bb44da_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["git_sha1"], name="packagedb_r_git_sha_be2e0f_idx"
            ),
        ),
    ]
