# Generated by Django 4.1.2 on 2023-07-06 00:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0068_alter_resource_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="The identifier of the Package set",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="package",
            name="package_sets",
            field=models.ManyToManyField(
                related_name="packages",
                to="packagedb.packageset",
                help_text="A set representing the Package sets this Package is a member of.",
            ),
        ),
    ]
