# Generated by Django 4.1.2 on 2023-07-06 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0070_auto_20230706_0045"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="package_set",
        ),
    ]
