# Generated by Django 4.1.2 on 2023-07-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0071_remove_package_package_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="created_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp set when a Package is created",
                null=True,
            ),
        ),
    ]
