# Generated by Django 4.1.2 on 2023-07-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0072_package_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="created_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp set when a Package is created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="history",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text='History for this object a text where each line has the form: "<timestamp><one space><message>". Append-only and not editable.',
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="last_modified_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp set when a Package is created or modified",
                null=True,
            ),
        ),
    ]
