# Generated by Django 4.1.2 on 2023-07-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0073_resource_created_date_resource_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="history_json",
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text='A list of mappings representing the history for this object. Each mapping contains the fields "timestamp" and "message".',
            ),
        ),
    ]
