# Generated by Django 4.1.2 on 2023-07-20 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0075_remove_package_history"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="history_json",
            new_name="history",
        ),
    ]
