# Generated by Django 4.1.2 on 2023-07-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0075_populate_history_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="history_json",
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text='A list of mappings representing the history for this object. Each mapping contains the fields "timestamp" and "message".',
            ),
        ),
    ]
