# Generated by Django 4.1.2 on 2023-07-20 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0076_resource_history_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="history",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="history",
        ),
    ]
