# Generated by Django 4.1.2 on 2023-09-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0077_remove_package_declared_license_expression_spdx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="release_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The date and time that the package file was created, or when it was posted to its original download source.",
                null=True,
            ),
        ),
    ]
