# Generated by Django 4.1.2 on 2023-11-07 00:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0079_alter_package_name_alter_package_namespace_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="package",
            name="packagedb_p_search__8d33bb_gin",
        ),
        migrations.RemoveField(
            model_name="package",
            name="search_vector",
        ),
    ]
