# Generated by Django 4.2.6 on 2023-12-06 01:02

from django.db import migrations
import packagedb.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("packagedb", "0080_remove_package_packagedb_p_search__8d33bb_gin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", packagedb.models.ApiUserManager()),
            ],
        ),
    ]
