# Generated by Django 4.2.6 on 2024-01-09 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0081_apiuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApiUser",
        ),
    ]
