# Generated by Django 4.2.6 on 2024-01-10 07:41

from django.db import migrations, models
import packagedb.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("packagedb", "0081_apiuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageWatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The identifier of the PackageWatch.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "package_url",
                    models.CharField(
                        db_index=True,
                        help_text="PackageURL to watch.",
                        max_length=2048,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="A short code to identify the type of this package.",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Package name prefix, such as Maven groupid, Docker image owner, GitHub user or organization, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Name of the package.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "depth",
                    models.CharField(
                        choices=[
                            ("version", "Version"),
                            ("metadata", "Metadata"),
                            ("scan", "Scan"),
                        ],
                        default="version",
                        help_text="Select the depth of data collection.",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        db_index=True,
                        default="daily",
                        help_text="Select how often the package should be watched.",
                        max_length=20,
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when this watch object was created.",
                    ),
                ),
                (
                    "last_watch_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp indicating when this watch object was last processed",
                        null=True,
                    ),
                ),
                (
                    "watch_error",
                    models.TextField(
                        blank=True,
                        help_text="Watch error messages. When present this means the watch failed.",
                        null=True,
                    ),
                ),
            ],
            bases=(models.Model, packagedb.models.UpdateMixin),
        ),
    ]
