# Generated by Django 5.0.1 on 2024-03-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0083_delete_apiuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="Descriptive file type for this resource.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="mime_type",
            field=models.CharField(
                blank=True,
                help_text="MIME type (aka. media type) for this resource. See https://en.wikipedia.org/wiki/Media_type",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="programming_language",
            field=models.CharField(
                blank=True,
                help_text="Programming language of this resource if this is a code file.",
                max_length=50,
                null=True,
            ),
        ),
    ]
