# Generated by Django 5.0.4 on 2024-04-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "packagedb",
            "0084_alter_resource_file_type_alter_resource_mime_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagerelation",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("source_package", "Source Package"),
                    ("binary_package", "Binary Package"),
                ],
                help_text='Relationship between the from and to package URLs such as "source_package" when a package is the source code package for another package.',
                max_length=30,
            ),
        ),
    ]
