# Generated by Django 5.0.7 on 2024-10-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0085_alter_packagerelation_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of this party.", max_length=255, null=True
            ),
        ),
    ]
