# Generated by Django 5.1.2 on 2024-11-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0086_alter_party_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dependentpackage",
            old_name="is_resolved",
            new_name="is_pinned",
        ),
    ]
