# Generated by Django 5.1.2 on 2024-12-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0087_rename_discovered_dependency_attribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={},
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={},
        ),
    ]
