# Generated by Django 5.1.2 on 2024-12-11 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0088_alter_package_md5_alter_package_sha1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The identifier of the Package set",
                        unique=True,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Author of package activity.", max_length=300
                    ),
                ),
                ("content", models.JSONField(help_text="Package activity content.")),
                (
                    "activity_update_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp indicating when original activity was last updated.",
                        null=True,
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when this object was created.",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="True if this activity has been processed.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
