# Generated by Django 5.1.5 on 2025-02-21 01:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0089_packageactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packageactivity",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="The identifier of the package activity",
                unique=True,
            ),
        ),
    ]
