# Generated by Django 5.1.5 on 2025-03-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0090_alter_packageactivity_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="is_duplicate",
            field=models.BooleanField(
                default=False,
                help_text="True if this Package is a duplicate of another Package",
            ),
        ),
    ]
