# Generated by Django 5.1.5 on 2025-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0091_package_is_duplicate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="email",
            field=models.CharField(
                blank=True,
                help_text="Email for this party.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of this party.", max_length=1024, null=True
            ),
        ),
    ]
