# Generated by Django 5.1.5 on 2026-08-04 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0094_package_packagedb_p_package_d39839_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageHealthMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Health metrics data for this Package",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when these health metrics were recorded.",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        help_text="The Package that these health metrics are related to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_metrics",
                        to="packagedb.package",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "package health metrics",
                "ordering": ["-creation_date"],
            },
        ),
    ]
