# Generated by Django 5.1.13 on 2026-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0094_package_packagedb_p_package_d39839_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcsAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_vcs_purl', models.CharField(db_index=True, max_length=2048)),
                ('new_vcs_purl', models.CharField(db_index=True, max_length=2048)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['old_vcs_purl'], name='packagedb_v_old_vcs_88807e_idx'), models.Index(fields=['new_vcs_purl'], name='packagedb_v_new_vcs_0f8a3b_idx')],
                'unique_together': {('old_vcs_purl', 'new_vcs_purl')},
            },
        ),
    ]
