# Generated by Django 5.1.13 on 2026-03-11 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0094_package_packagedb_p_package_d39839_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="File name of the metadata file as collected from upstream",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Content of the metadata file", null=True
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        help_text="The Package that this metadata file is from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_files",
                        to="packagedb.package",
                    ),
                ),
            ],
        ),
    ]
