# Generated by Django 5.1.13 on 2026-03-20 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0094_package_packagedb_p_package_d39839_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageMetadataFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Name of the metadata file, e.g. 'package.json'",
                        max_length=255,
                    ),
                ),
                (
                    "filetype",
                    models.CharField(
                        blank=True,
                        help_text="Type of metadata file, e.g. 'npm', 'pypi', 'maven'",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The raw text content of the metadata file",
                        null=True,
                    ),
                ),
                (
                    "download_url",
                    models.CharField(
                        blank=True,
                        help_text="URL from which this metadata file was retrieved",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "sha1",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA1 checksum of the file content",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        help_text="The Package this metadata file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_files",
                        to="packagedb.package",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("package", "filename")},
            },
        ),
    ]
