# Generated by Django 6.0.6 on 2026-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0094_package_packagedb_p_package_d39839_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["vcs_url"], name="packagedb_p_vcs_url_fa3a4f_idx"
            ),
        ),
    ]
