# Generated by Django 5.2.17 on 2026-09-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0094_package_packagedb_p_package_d39839_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="package_content",
            field=models.IntegerField(
                choices=[
                    (1, "curation"),
                    (2, "patch"),
                    (3, "source_repo"),
                    (4, "source_archive"),
                    (5, "binary"),
                    (6, "test"),
                    (7, "doc"),
                    (8, "base_package"),
                ],
                help_text="Content of this Package as one of: curation, patch, source_repo, source_archive, binary, test, doc, base_package",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ScoringModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ecosystem",
                    models.CharField(
                        help_text="Package ecosystem this scoring model applies to, for example npm, pypi, maven.",
                        max_length=32,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        help_text="Version of this scoring model definition, for example 1.0.",
                        max_length=32,
                    ),
                ),
                (
                    "scoring_model",
                    models.CharField(
                        help_text="Scoring approach, for example health or scorecard.",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "scoring models",
                "ordering": ["ecosystem", "scoring_model", "model_version"],
                "unique_together": {("ecosystem", "scoring_model", "model_version")},
            },
        ),
        migrations.CreateModel(
            name="PackageHealthMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Package version these health metrics were collected for. For V1 (versionless npm PURLs), this is the latest version at collection time.",
                        max_length=100,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Health metrics data for this Package",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        help_text="Overall health score for this Package at collection time.",
                    ),
                ),
                (
                    "date_collected",
                    models.DateTimeField(
                        help_text="Timestamp indicating when these health metrics were collected."
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        help_text="The Package that these health metrics are related to, for example pkg:github/leftpad/leftpad",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_metrics",
                        to="packagedb.package",
                    ),
                ),
                (
                    "scoring_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scoring model used to produce these metrics.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_metrics",
                        to="packagedb.scoringmodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "package health metrics",
                "ordering": ["-date_collected"],
                "unique_together": {("package", "version", "date_collected")},
            },
        ),
    ]
