# Generated by Django 5.1.5 on 2026-08-04 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("packagedb", "0095_packagehealthmetrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagehealthmetrics",
            name="version",
            field=models.CharField(
                default="",
                help_text=(
                    "Package version these health metrics were collected for. "
                    "For V1 (versionless npm PURLs), this is the latest version at "
                    "collection time."
                ),
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="packagehealthmetrics",
            name="date_collected",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp indicating when these health metrics were collected.",
            ),
        ),
        migrations.RemoveField(
            model_name="packagehealthmetrics",
            name="creation_date",
        ),
        migrations.AlterModelOptions(
            name="packagehealthmetrics",
            options={
                "ordering": ["-date_collected"],
                "verbose_name_plural": "package health metrics",
            },
        ),
        migrations.AlterUniqueTogether(
            name="packagehealthmetrics",
            unique_together={("package", "version", "date_collected")},
        ),
    ]
