parameters:
    job_name: ''
    image_name: ''
    python_versions: []
    test_suites: {}
    python_architecture: x64

jobs:
    - job: ${{ parameters.job_name }}

      pool:
          vmImage: ${{ parameters.image_name }}

      strategy:
          matrix:
              ${{ each tsuite in parameters.test_suites }}:
                 ${{ tsuite.key }}:
                     test_suite_label: ${{ tsuite.key }}
                     test_suite: ${{ tsuite.value }}

      services:
        postgres: postgres

      steps:
          - checkout: self
            fetchDepth: 10

          - ${{ each pyver in parameters.python_versions }}:
              - task: UsePythonVersion@0
                inputs:
                    versionSpec: '${{ pyver }}'
                    architecture: '${{ parameters.python_architecture }}'
                displayName: '${{ pyver }} - Install Python'

              - script: |
                    make dev
                    make envfile_testing
                    sudo mkdir /etc/purldb
                    sudo cp .env /etc/purldb
                    sudo mkdir /etc/scancodeio
                    sudo cp .env /etc/scancodeio
                displayName: '${{ pyver }} - Configure'

              - script: make check
                displayName: '${{ pyver }} - Check code style and format'

              - script: $(test_suite)
                displayName: '${{ pyver }} - $(test_suite_label) on ${{ parameters.job_name }}'
