# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_auto_20160712_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceuri',
            name='map_error',
            field=models.TextField(blank=True, help_text='Mapping errors messages. When present this means the mapping failed.', null=True),
        ),
    ]
