# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 15:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_auto_20160713_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceuri',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Json serialized text of metadata of a ResourceURI. This contains the data that was transformed or parsed  to represent the metadata of the ResourceURI', null=True),
        ),
    ]
