# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_resourceuri_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceuri',
            name='metadata',
        ),
    ]
