# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0008_change_default_sort_order_on_resourceuri'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceuri',
            name='source_uri',
            field=models.CharField(blank=True, help_text='Optional: real source remote URI for this visit.For example for a package repository index is a typical source via which a first level of package data is fetched. And it is not the URI in the uri field. It is just the source of the fetchOr the source may be a mirror URI used for fetching.', max_length=2048, null=True),
        ),
    ]
