# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0010_resourceuri_mining_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceuri',
            name='is_mappable',
            field=models.BooleanField(db_index=True, default=False, help_text='When set to True (Yes), this field indicates that this URI is mappable in the sense that there is a mapper route available to process it.'),
        ),
        migrations.AddField(
            model_name='resourceuri',
            name='is_visitable',
            field=models.BooleanField(db_index=True, default=False, help_text='When set to True (Yes), this field indicates that this URI is visitable in the sense that there is a visitor route available to process it.'),
        ),
        migrations.AlterField(
            model_name='resourceuri',
            name='last_map_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp set to the date of the last mapping. Used to track mapping status.', null=True),
        ),
    ]
