# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0011_auto_20170807_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceuri',
            options={'verbose_name': 'Resource URI'},
        ),
    ]
