# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0014_auto_20170807_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceuri',
            name='wip_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Work In Progress. This is a timestamp set at the start of a visit or mapping or indexing or null when no processing is in progress.', null=True),
        ),
    ]
