# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0015_auto_20180607_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceuri',
            name='sig',
        ),
    ]
