# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packagedb', '0023_package_source_packages'),
        ('discovery', '0020_resourceuri_package_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannableuri',
            name='package_id',
        ),
        migrations.AddField(
            model_name='scannableuri',
            name='package',
            field=models.ForeignKey(help_text='The Package that this ScannableURI is for', on_delete=django.db.models.deletion.CASCADE, to='packagedb.Package'),
            preserve_default=False,
        ),
    ]
