#
# Copyright (c) nexB Inc. and others. All rights reserved.
# purldb is a trademark of nexB Inc.
# SPDX-License-Identifier: Apache-2.0
# See http://www.apache.org/licenses/LICENSE-2.0 for the license text.
# See https://github.com/aboutcode-org/purldb for support or download.
# See https://aboutcode.org for more information about nexB OSS projects.
#


"""
Structure: {'sf.net': 'dje'}
"""

SFNET_PROGRAMMING_LANGUAGES = {
    'ALGOL 68': 'Algol',
    'APL': 'APL',
    'ASP': 'ASP',
    'ASP.NET': 'ASP',
    'AWK': 'Awk',
    'ActionScript': 'ActionScript',
    'Ada': 'Ada',
    'AppleScript': 'AppleScript',
    'AspectJ': 'AspectJ',
    'Assembly': 'Assembly',
    'AutoIt': 'AutoIt',
    'BASIC': 'Visual Basic',
    'BlitzMax': 'BlitzMax',
    'Boo': 'Boo',
    'C': 'C',
    'C#': 'C#',
    'C++': 'C++',
    'COBOL': 'COBOL',
    'Clarion': 'Clarion',
    'Cold Fusion': 'ColdFusion',
    'Common Lisp': 'Common Lisp',
    'Curl': 'Curl',
    'D': 'D',
    'Delphi/Kylix': 'Delphi/Object Pascal',
    'Dylan': 'Dylan',
    'Eiffel': 'Eiffel',
    'Emacs-Lisp': 'Emacs Lisp',
    'Erlang': 'Erlang',
    'Euler': 'Euler',
    'Euphoria': 'Euphoria',
    'Flex': 'Flex',
    'Forth': 'Forth',
    'Fortran': 'Fortran',
    'Free Pascal': 'Pascal',
    'GLSL (OpenGL Shading Language)': 'GLSL (OpenGL Shading Language)',
    'Groovy': 'Groovy',
    'Haskell': 'Haskell',
    'IDL': 'IDL',
    'JSP': 'Java',
    'Java': 'Java',
    'JavaScript': 'JavaScript',
    'Kaya': 'Kaya',
    'LPC': 'LPC',
    'LabVIEW': 'LabVIEW',
    'Lazarus': 'Pascal',
    'Lisp': 'Lisp',
    'Logo': 'Logo',
    'LotusScript': 'LotusScript',
    'Lua': 'Lua',
    'MATLAB': 'MATLAB',
    'MUMPS': 'MUMPS',
    'Mathematica': 'Mathematica',
    'Modula': 'Modula',
    'OCaml (Objective Caml)': 'OCaml',
    'Oberon': 'Oberon',
    'Object Pascal': 'Delphi/Object Pascal',
    'Objective C': 'Objective-C',
    'Objective-C 2.0': 'Objective-C',
    'Oz': 'Oz',
    'PHP': 'PHP',
    'PL/SQL': 'PL/SQL',
    'PROGRESS': 'Progress 4GL',
    'Pascal': 'Pascal',
    'Perl': 'Perl',
    'Pike': 'Pike',
    'Prolog': 'Prolog',
    'Python': 'Python',
    'REALbasic': 'REALBasic',
    'REBOL': 'REBOL',
    'Rexx': 'REXX',
    'Ruby': 'Ruby',
    'S/R': 'SR',
    'Scala': 'Scala',
    'Scheme': 'Scheme',
    'Scilab': 'Scilab',
    'Scriptol': 'Scriptol',
    'Simulink': 'Simulink',
    'Smalltalk': 'Smalltalk',
    'Standard ML': 'Standard ML',
    'Tcl': 'Tcl',
    'Transcript/Revolution': 'Revolution',
    'Unix Shell': 'Shell',
    'VBScript': 'VBScript',
    'VHDL/Verilog': 'Verilog',
    'Visual Basic': '(Visual) Basic',
    'Visual Basic .NET': 'Visual Basic .NET',
    'Visual Basic for Applications (VBA)': '(Visual) Basic',
    'Visual FoxPro': '(Visual) FoxPro',
    'XBase/Clipper': 'Clipper',
    'XBasic': 'XBasic',
    'XSL (XSLT/XPath/XSL-FO)': 'XSLT',
    'Yacc': 'yacc',
    'haXe': 'haXe',
}
